# Generated by Django 2.1.5 on 2020-03-09 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('name_project', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('interior_number', models.CharField(blank=True, max_length=7, null=True, verbose_name='Numero interior')),
                ('outdoor_number', models.CharField(blank=True, max_length=7, null=True, verbose_name='Numero exterior')),
                ('cp', models.CharField(max_length=16, verbose_name='Codigo postal')),
                ('suburn', models.CharField(max_length=255, verbose_name='Colonia')),
                ('location', models.CharField(max_length=255, verbose_name='localidad')),
                ('municipality', models.CharField(max_length=255, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('latitude', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, max_length=255, null=True, verbose_name='longitud')),
                ('photos', models.ManyToManyField(related_name='photos', to='files.ImageProject')),
                ('user', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created', 'update'),
            },
        ),
    ]
