# Generated by Django 2.1.5 on 2020-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('file_doc_img', models.FileField(blank=True, null=True, upload_to='Docs/proyect/accounting')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('file_doc_img', models.FileField(blank=True, null=True, upload_to='Docs/proyect/construction_control')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ConstructionResidentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('file_doc_img', models.FileField(blank=True, null=True, upload_to='Docs/proyect/construction_resident')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='JuridicalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('file_doc_img', models.FileField(blank=True, null=True, upload_to='Docs/proyect/juridical')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='MarketingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='El el tiempo en que el objeto fue creado', verbose_name='Fecha de creacion')),
                ('update', models.DateTimeField(auto_now=True, help_text='Es el tiempo en que el objeto se actualizo', verbose_name='Fecha de actualizacion')),
                ('file_doc_img', models.FileField(blank=True, null=True, upload_to='Docs/proyect/marketing')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
